package com.ibm.entity;

public enum STATUS {
	NEW, ASSIGNED, OPEN, FIXED, PENDING_RETEST, RETEST, REOPEN, VERIFIED, CLOSED, REJECTED, DUPLICATE, DEFERRED,
	NOT_A_BUG, COULD_NOT_REPRODUCE, WONT_FIX, NEED_MORE_INFO
}
