package com.ibm.entity;

public enum STATUS {
	NEW, ASSIGNED, OPEN, FIXED, PENDING_RETEST, RETEST, REOPEN, VERIFIED, CLOSED, REJECTED, DUPLICATE, DEFERRED,
	NOT_A_BUG, NEED_MORE_INFO, WONT_FIX, COULD_NOT_REPRODUCE
}
